name: New Post
description: Add or edit a post
title: '[POST]'
labels:
- post
body:
- type: dropdown
  id: location_name
  attributes:
    label: Location
    options:
    - Melbourne, Australia
    - Istanbul, Turkey
    - "Tiran\xEB, Albania"
    - "Kor\xE7\xEB, Albania"
    - Berat, Albania
    - The Accursed Mountains
    - Budva, Montenegro
    - Podgorica, Montenegro
    - Ljubljana, Slovenia
    - Bohinj, Slovenia
    - Julian Alps, Slovenia
    - Vipava Valley, Slovenia
    - Trieste, Italy
    - Valpolicella, Italy
    - Dolomites, Italy
    - Munich, Germany
    - Vienna, Austria
    - Tatra Mountains, Slovakia
    - Krakow, Poland
    - Prague, Czechia
    - Georgia
    - Armenia
    - Kazakhstan
    - Uzbekistan
    - India
    - Taiwan
    - China
    - Thailand
  validations:
    required: true
- type: input
  id: title
  attributes:
    label: Post title
    placeholder: Colosseum visit
  validations:
    required: true
- type: textarea
  id: text
  attributes:
    label: Post text
- type: textarea
  id: photos
  attributes:
    label: Photo URLs (one per line)
    placeholder: 'https://example.com

      https://example.com

      '
